### ISSUE TITLE
 Enhance GitHub Actions Workflow for Release Management in IdentityServer8

### ISSUE THREAD

**Issue by alexhiggins732** [alexhiggins732/IdentityServer8#32]
## Overview

We're looking to improve our CI/CD process in the IdentityServer8 project by automating the release process with GitHub Actions. This will involve modifying the existing workflow which handles version tagging using the Git Flow branching strategy, GitHub release creation, and binary publication. 

## Goals

- Automating the push of Git tags during push commits to develop, release or master branches.
- Automate the creation of a new GitHub release when a commit is tagged with a version number in the main branch.
- Ensure that version tags are pushed to the repository alongside regular code commits.
- Configure the workflow to publish binaries/executables and NuGet packages to the GitHub release as part of the GitHub release.

## Tasks

- [ ] Update the `.github/workflows` configuration to trigger the modified workflow on version tag creation.
- [ ] Add a step in the workflow to create a GitHub release.
- [ ] Ensure the workflow compiles the code and attaches the resulting binaries to the GitHub release.
- [ ] Push the Git tag upon successful creation of artifacts and passing unit tests.
- [ ] Document the process in the project's README or CONTRIBUTING guide.

## Acceptance Criteria

- A commit tagged with a version number (e.g., `v1.0.0`) should trigger the new release workflow.
- The workflow should result in a new GitHub release with the corresponding version tag.
- The release should include downloadable binaries for the project.
- The process should be documented for maintainers and contributors to understand how releases are made.

## Additional Context

This enhancement will streamline our release process, making it easier for maintainers to publish new versions and for users to download the latest updates of IdentityServer8.

This issue is labeled as a `good first issue` because it is a self-contained improvement that is ideal for new contributors looking to familiarize themselves with our project and the GitHub Actions platform.

## Helpful Resources

- [GitHub Actions Documentation](https://docs.github.com/en/actions)
- [Creating GitHub Releases with Actions](https://docs.github.com/en/actions/guides/publishing-nodejs-packages#publishing-packages-to-github-packages-and-other-registries)
- [About GitHub Actions for CI/CD](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions)

We welcome contributions from all, and we're excited to see your pull requests!

**Comment by garethdhopkins** [comment]
Looking at this now, but have a few questions:-

- Tagging a commit with a version (e.g. v1.0.0) on main (master?) only should trigger the release process?
- In this goal: _Automating the push of Git tags during push commits to develop, release or master branches._ - what Git tags should be auto created on commits to these branches? I've looked back through past commits and can't see anything other than the release tags all on the master branch in the repo.
- I'm assuming we rely on the those versions in the code are to be changed before tagging the release? e.g. (Directory.Build.props, docs/conf.py, version.json) We shouldn't we inject said versions in the various version files/vars in the project builds?

**Comment by garethdhopkins** [comment]
Made a first pass on this to get the conversation going on this issue. Not personally very experienced with GitHub actions/workflows but have some experience in DevOps and it's fairly similar. 

I've not done any Nuget publishing as part of this workflow, assuming the other workflows would handle that but we could merge this with the master workflow?

Let me know your thoughts.

**Comment by garethdhopkins** [comment]
Right, been testing this on my fork and it's now creating a release when tagged with a tag matching "v*" - and it zips the output and attaches to the release. Comparing previous releases on this project it includes all of the nuget packages. Do we want that to happen here?

**Comment by garethdhopkins** [comment]
Spent waay too long on trying to get the tag annotation for the Release name and ended up just hardcoding 'IdentityServer8 Release ' + TagName..

A few other improvements, checks the packages.json version matches the tag name and exits workflow if not.

Will make created Release 'prerelease:true' if the release version has a dash in it, e.g. '-alpha' or '-beta' - if you can think of any reason why a dash would be in a proper release let me know.

Added nuget packages to try and match with previous releases, but my version zips them for ease but can work on separating them if needed? Should just be a case of looping through the files in the directory and adding them as assets.

Also, happy to flatten the mess of commits into a single commit, probably makes sense as most of it is me debugging various scenarios and having to commit to test on GitHub on my fork.

**Comment by alexhiggins732** [comment]
Following SemVer2, there should only be a dash in prelease, so that is on target. I am using NerdBank Git Version to get the SemVer2 for packaging at the moment but have a custom version tool that works better I plan on making open source:

```
    - uses: dotnet/nbgv@master
      id: nbgv

    - name: Display Package Version
      run: echo "PackageVersion=${{ steps.nbgv.outputs.SemVer2 }}"
```

The current Gitflow actions are here. 
https://github.com/alexhiggins732/IdentityServer8/blob/master/.github/workflows/

I tried a few different attempts to get releases pushed to Github and then gave up, so appreciate the PR. Will need to integrate your PR into those flows.

Another issue at the moment is I am running the build and test matrix for Windows, Mac, and Linux.

However, the Ubuntu build keeps failing complaining it can't find DoNet 8.0.1xxx even though the build is configured to use DotNet latest which is much newer than 8.0.1.

```
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macOS-latest, ubuntu-latest, windows-latest]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v3
      with:        
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
```

**Comment by garethdhopkins** [comment]
It's nice to get involved, ultimately I'd like to use this on a commercial project that I work on, that currently still uses identityserver4, so it would be great if we could maintain it and it was a viable upgrade path for that project. 

I think my commit (https://github.com/alexhiggins732/IdentityServer8/pull/50/commits/137a84a298be1c649b784658afab6a6e504434d1) fixes that issue on ubuntu - just makes it a bit looser in which .net8 version it can use - not sure why ubuntu has a different behaviour but my workflow which is set to ubuntu-latest built fine on the last couple of runs on my fork. I removed the matrix build for the tagged-release workflow, but happy to put it back.

I did use those existing workflows as a basis to this new tagged-release one, and there's a question of whether we modify those existing workflows so they don't do certain steps, like push to nuget and only the tagged-release workflow pushes to nuget as both pre releases and proper releases?

**Comment by quickstar** [comment]
Hi @alexhiggins732 and @garethdhopkins,

Following the discussion on enhancing the release workflow, I wanted to share the automated release process I've implemented in my projects. It might offer some ideas or patterns that could be adapted for IdentityServer8, especially regarding automated versioning, multi-channel releases, and artifact publishing.

My approach uses a specific branching strategy tied directly to release channels and relies heavily on CI/CD automation driven by conventional commits.

**Branch Strategy & Release Channels**

| Branch          | Channel | Prerelease | Purpose             | Trigger                |
| --------------- | ------- | ---------- | ------------------- | ---------------------- |
| `main`          | default | false      | Production releases | Merge/Push             |
| `develop`       | beta    | `beta`     | Beta testing        | Merge/Push             |
| `preview-*`     | alpha   | `true`     | Alpha testing       | Push                   |
| `[0-9]+.[0-9x]+.x` | hotfix  | false      | Emergency fixes     | Push (usually from `main`) |

**Versioning & Release Automation**

*   **Semantic Versioning:** Version bumps (`Major`, `Minor`, `Patch`) are determined automatically based on **conventional commit messages** (`BREAKING CHANGE`, `feat`, `fix`).
*   **CI/CD Triggered Releases:** Pushes to the branches listed above trigger the corresponding release workflow (Alpha, Beta, Production, Hotfix).
*   **Automated Actions:** The CI/CD pipeline handles:
    *   Running tests.
    *   Calculating the next semantic version based on commits since the last tag on that channel.
    *   Building artifacts (NuGet packages, Windows & Linux Docker images).
    *   Tagging the commit with the new version.
    *   Creating a GitHub Release with an automatically generated changelog based on commit messages.
    *   Uploading artifacts to the GitHub Release.
    *   Publishing NuGet packages to GitHub Packages.
    *   Publishing Docker images (tagged with version and channel) to GitHub Container Registry (`ghcr.io`).

**Workflow Visualization**

Here's a sequence diagram illustrating the general flow for different release types:

```mermaid
%%{init: {
  'theme': 'base',
  'themeVariables': {
    'primaryColor': '#282a36',
    'primaryTextColor': '#f8f8f2',
    'primaryBorderColor': '#6272a4',
    'lineColor': '#6272a4',
    'secondaryColor': '#44475a',
    'secondaryTextColor': '#f8f8f2',
    'secondaryBorderColor': '#bd93f9',
    'tertiaryColor': '#282a36',
    'tertiaryTextColor': '#f8f8f2',
    'tertiaryBorderColor': '#ff79c6',
    'noteBkgColor': '#282a36',
    'noteTextColor': '#f8f8f2',
    'noteBorderColor': '#ff5555',
    'activeParticipant': '#50fa7b',
    'sequenceNumberColor': '#50fa7b',
    'actorLineColor': '#bd93f9',
    'actorBorder': '#bd93f9',
    'actorBackground': '#44475a',
    'actorTextColor': '#f8f8f2',
    'messageFontWeight': 'bold',
    'fontFamily': 'monaco'
  }
}}%%

sequenceDiagram
    participant FB as feature/*
    participant PB as preview-*
    participant D as develop
    participant M as main
    participant CI as CI/CD
    participant GH as GitHub

    Note over FB,M: Regular Feature Development
    FB->>CI: Push to feature branch
    CI->>CI: Run unit tests only

    FB->>D: Merge to develop
    D->>CI: Push to develop
    CI->>CI: Run tests

    rect rgb(40, 42, 54)
        Note right of CI: Beta Release Process
        CI->>CI: Generate beta version<br/>(e.g. 1.2.0-beta.1)
        CI->>CI: Build artifacts<br/>(NuGet, Docker images)
        CI->>GH: Create beta release
        CI->>GH: Upload artifacts
        CI->>GH: Publish to registry
    end

    Note over PB,M: Preview Feature Development
    PB->>CI: Push to preview-* branch
    CI->>CI: Run tests

    rect rgb(40, 42, 54)
        Note right of CI: Alpha Release Process
        CI->>CI: Generate alpha version<br/>(e.g. 1.2.0-alpha.1)
        CI->>CI: Build artifacts<br/>(NuGet, Docker images)
        CI->>GH: Create alpha release
        CI->>GH: Upload artifacts
        CI->>GH: Publish to registry
    end

    Note over D,M: Release Process
    D->>M: Pull Request to main
    M->>CI: Merge to main
    CI->>CI: Run tests

    rect rgb(40, 42, 54)
        Note right of CI: Production Release Process
        CI->>CI: Generate release version<br/>(e.g. 1.2.0)
        CI->>CI: Build artifacts<br/>(NuGet, Docker images)
        CI->>GH: Create release
        CI->>GH: Upload artifacts
        CI->>GH: Publish to registry
    end

    Note over M,GH: Hotfix Process
    M->>CI: Push hotfix to main
    CI->>CI: Run tests

    rect rgb(40, 42, 54)
        Note right of CI: Hotfix Release Process
        CI->>CI: Generate patch version<br/>(e.g. 1.2.1)
        CI->>CI: Build artifacts<br/>(NuGet, Docker images)
        CI->>GH: Create release
        CI->>GH: Upload artifacts
        CI->>GH: Publish to registry
    end
    CI->>D: Sync version back (Optional: if needed)
```

**(Note:** The diagram simplifies some steps like explicit tagging and changelog generation, which are part of the CI process.)

This setup provides a clear, fully automated way to manage different release types based on branch activity and standardized commit messages. It leverages tools often associated with the `semantic-release` ecosystem (though the specific tooling can vary).

I'd be happy to elaborate further on any part of this process (e.g., specific GitHub Actions workflow configurations, conventional commit setup, `semantic-release` tooling) or help adapt relevant parts if it seems useful for IdentityServer8's goals.

Let me know your thoughts!
